### ISSUE TITLE
Week 9 feedback from ch3859

### ISSUE THREAD

**Issue by ChaoNyu** [cerbveen/comp-lab-class#2]
Good job for week9. Great pictures with clear explanations.

**Comment by ChaoNyu** [comment]
I've just noticed that there might be a problem when calculating the g_11 and g_22 rdf functions. You'll need to exclude the first count in the InterRDF results because it's the RDF of the atom with itself and it's always zero.

**Comment by cerbveen** [comment]
Thank you! I have revised it!
